  - name: group "tomcat_as_group"
    group: name={{tomcat_group}}
    become: yes

  - name: user "tomcat_as"
    user: name='{{tomcat_user}}' group='{{tomcat_group}}' home='{{tomcat_home}}'
    become: yes

  - name: get tomcat ver. {{tomcat_version}}
    unarchive: 
      src: '{{tomcat_download_uri}}'
      dest: '{{tomcat_home}}'
      remote_src: True
      creates: '{{tomcat_home}}/{{tomcat_unarchived}}'
    become: yes
    become_user: '{{tomcat_user}}' 

  - name: rename tomcat dir
    command: mv {{tomcat_home}}/{{tomcat_unarchived}} {{tomcat_home}}/{{tomcat_version}} creates={{tomcat_home}}/{{tomcat_version}}
    become: yes
    become_user: '{{tomcat_user}}'
  
  - name: tomcat users
    template:
      src: tomcat-users.j2
      dest: '{{tomcat_home}}/{{tomcat_version}}/conf/tomcat-users.xml'
    become: yes
    become_user: '{{tomcat_user}}'

  - name: startup script
    template:
      src: tomcat.service.j2
      dest: /etc/rc.d/init.d/tomcat
      mode : a+x
    become: yes

  - name: tomcat {{tomcat_version}} started
    service: name=tomcat state=started
    become: yes
    become_user: '{{tomcat_user}}'

  - shell: |
      res=`/sbin/service tomcat status`
      if [[ $res == 'Tomcat is running' ]]; then echo STARTED; fi
    register: result
  - name: debug
    debug: 
      msg: "Tomcat status: {{result.stdout}}"
