- name: webserver provision
  hosts: localhost
  
  vars:
    option: started

  tasks:
  - name: debug
    debug: 
      msg: "Launched with option: {{option}}"

  - name: vagrant provision
    prov: path=../resources/virtualbox/Vagrantfile state={{option}}
    register: vagrant_vars
  - debug: msg={{vagrant_vars}}
  - add_host:
      name: web_server
      ansible_host: "{{vagrant_vars.ip}}"
      ansible_port: "{{vagrant_vars.port}}"
      ansible_user: "{{vagrant_vars.user}}"
      ansible_connection: "ssh"       
      ansible_ssh_private_key_file: "{{vagrant_vars.key}}"
    when: vagrant_vars.status == "running"
